#!/usr/bin/env python3
"""
DBUnit XML to SQL Converter
Converts DBUnit XML datasets to PostgreSQL-compatible SQL INSERT statements.

Usage:
    python3 xml-to-sql.py <input.xml> <output.sql>
    
Example:
    python3 xml-to-sql.py storage-e2e.xml storage-e2e.generated.sql

This script is used by load-test-fixtures.sh to generate SQL on-demand from
authoritative DBUnit XML datasets. The generated SQL files are never committed
to git (see .gitignore).
"""

import sys
import xml.etree.ElementTree as ET
from pathlib import Path


def xml_to_sql(xml_file: Path, sql_file: Path):
    """Convert DBUnit XML to SQL INSERT statements."""

    # Parse XML
    tree = ET.parse(xml_file)
    root = tree.getroot()

    statements = []
    statements.append("-- Generated from: {}".format(xml_file.name))
    statements.append("-- DO NOT EDIT - This file is auto-generated from DBUnit XML")
    statements.append("-- Generated by: xml-to-sql.py")
    statements.append("")

    # Track max ID per table for sequence updates
    table_max_ids = {}

    # Process each table element
    for table in root:
        table_name = table.tag
        columns = []
        values = []

        for attr_name, attr_value in table.attrib.items():
            columns.append(attr_name)

            # Track max ID for sequence updates
            if attr_name.lower() == 'id' and attr_value.isdigit():
                current_id = int(attr_value)
                if table_name not in table_max_ids:
                    table_max_ids[table_name] = current_id
                else:
                    table_max_ids[table_name] = max(table_max_ids[table_name], current_id)

            # Handle NULL values (empty string in DBUnit XML)
            if attr_value == "":
                values.append("NULL")
            # Handle boolean values
            elif attr_value.lower() in ("true", "false"):
                values.append(attr_value.upper())
            # Handle numeric values (integers and decimals)
            elif attr_value.replace(".", "", 1).replace("-", "", 1).isdigit():
                values.append(attr_value)
            # Handle string values (quote and escape)
            else:
                # Escape single quotes by doubling them (PostgreSQL standard)
                escaped_value = attr_value.replace("'", "''")
                values.append("'{}'".format(escaped_value))

        # Build INSERT statement
        insert_stmt = "INSERT INTO {} ({}) VALUES ({});".format(
            table_name,
            ", ".join(columns),
            ", ".join(values)
        )
        statements.append(insert_stmt)

    # Add sequence updates at the end
    if table_max_ids:
        statements.append("")
        statements.append("-- Update sequences to avoid ID conflicts after fixture data")
        for table_name, max_id in table_max_ids.items():
            # Sequence naming convention: table_name_seq
            seq_name = "{}_seq".format(table_name)
            # Set sequence to max_id + 1 to avoid conflicts
            setval_stmt = "SELECT setval('{}', {}, true);".format(seq_name, max_id)
            statements.append(setval_stmt)

    # Write to output file
    with open(sql_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(statements))
        f.write('\n')  # Final newline

    print("✅ Generated {} statements from {}".format(
        len(root),
        xml_file.name
    ))
    print("   Output: {}".format(sql_file))


def main():
    if len(sys.argv) != 3:
        print("Usage: {} <input.xml> <output.sql>".format(sys.argv[0]))
        print("\nExample:")
        print("  {} storage-e2e.xml storage-e2e.generated.sql".format(sys.argv[0]))
        sys.exit(1)
    
    xml_file = Path(sys.argv[1])
    sql_file = Path(sys.argv[2])
    
    if not xml_file.exists():
        print("ERROR: Input file not found: {}".format(xml_file))
        sys.exit(1)
    
    try:
        xml_to_sql(xml_file, sql_file)
    except Exception as e:
        print("ERROR: Failed to convert XML to SQL: {}".format(e))
        sys.exit(1)


if __name__ == "__main__":
    main()
